SAMPLES:
    - "SAMPLE1"
    - "SAMPLE1"
    - "SAMPLE3"
GENOME:
    - "/path/to/bowtie2/index"
# digest file make with the following command: 
# hicup_digester --arima genome.fa 
DIGEST:
    - "/path/to/hicup_digest/digest.txt"
CHRSIZES:
    - "/path/to/genome/chrom.sizes.tsv"
CHR:
    - "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chrX,chr8,chr9,chr11,chr10,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr20,chr19,chrY,chr22,chr21"
ASMBLY:
    - "hg38"
