SAMPLES:
    - "SAMPLE1"
    - "SAMPLE1"
    - "SAMPLE3"
MERGE_PFX:
    - "human_hic"
GENOME:
    - "/path/to/bowtie2/index"
# digest file make with the following command: 
# hicup_digester --arima genome.fa 
DIGEST:
    - "/path/to/hicup_digest/digest.txt"
CHRSIZES:
    - "/path/to/genome/chrom.sizes.tsv"
ASMBLY:
    - "hg38"
